spring:
  application:
    name: spring-cloud-api-gateway
server:
  port: 8083
zuul:
  prefix: /api
  routes:
    properties:
      path: /properties/**
      serviceId: spring-cloud-client-common
    peopleOne:
      path: /people-one/**
      serviceId: spring-cloud-client-one
    peopleTwo:
      path: /people-two/**
      serviceId: spring-cloud-client-two
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: true